info:
  app:
    description: Mastering Spring Boot from Amigos Code
    name: Spring Boot Master Class Course
    version: 1.0.0
  company:
    name: Amigos-code
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: on_param
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/springboot_amigos
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
  main:
    banner-mode: 'off'
  profiles:
    active: dev
